# --- BLUETOOTH STABILITÄT ---
# Erhöht die Bluetooth-Sendeleistung auf das Maximum
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Optimierungen für die Verbindung zwischen rechter und linker Hälfte (Ping-Rate erhöht)
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=6
CONFIG_BT_PERIPHERAL_PREF_LATENCY=16
CONFIG_BT_BUF_ACL_TX_COUNT=32
CONFIG_BT_L2CAP_TX_BUF_COUNT=32

# ZMK STABILITÄTS-FIXES
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_ZMK_BEHAVIORS_QUEUE_SIZE=512

# Displays und Stromversorgung anlassen
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_EXT_POWER=y

# --- DEEP SLEEP DEAKTIVIERT ---
# Wir schalten das Einschlafen zum Testen KOMPLETT AB.
CONFIG_ZMK_SLEEP=n
